spring.application.name=loan-sanction-service

server.port=4444

# ---------- Default Data Source (MySQL for Student) ----------
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/home_loan_loan_sanction
spring.datasource.username=root
spring.datasource.password=root


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
